# Generated by Django 4.2.3 on 2023-07-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_options_remove_student_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='students', to='school.teacher'),
        ),
    ]
